"""JWT validation for sandbox authentication.

This module handles resolver-side JWT validation. The sre-agent server
has its own auth.py for generation (they're separate Docker images).

Validates JWTs from sandboxes to ensure only legitimate sandboxes
can request credentials for their designated tenant/team.

The JWT is generated by the SRE Agent server when creating a sandbox,
embedded in the per-sandbox Envoy config, and sent to credential-resolver
via the x-sandbox-jwt header on every ext_authz request.

Note: JWT generation is in sre-agent/auth.py
"""

import os
from typing import NamedTuple

import jwt

# Shared secret with sre-agent server
# In production, load from K8s Secret (same secret in both deployments)
JWT_SECRET = os.getenv("JWT_SECRET", "incidentfox-sandbox-jwt-secret-change-in-prod")

# JWT settings (must match sre-agent/auth.py)
JWT_ALGORITHM = "HS256"
JWT_ISSUER = "incidentfox-server"
JWT_AUDIENCE = "credential-resolver"


class SandboxClaims(NamedTuple):
    """Claims extracted from a validated sandbox JWT."""

    tenant_id: str
    team_id: str
    sandbox_name: str
    thread_id: str


def validate_sandbox_jwt(token: str) -> SandboxClaims | None:
    """Validate a sandbox JWT and extract claims.

    Args:
        token: JWT string from x-sandbox-jwt header

    Returns:
        SandboxClaims if valid, None if invalid/expired
    """
    if not token:
        return None

    try:
        payload = jwt.decode(
            token,
            JWT_SECRET,
            algorithms=[JWT_ALGORITHM],
            issuer=JWT_ISSUER,
            audience=JWT_AUDIENCE,
        )
        return SandboxClaims(
            tenant_id=payload["tenant_id"],
            team_id=payload["team_id"],
            sandbox_name=payload["sandbox_name"],
            thread_id=payload["thread_id"],
        )
    except jwt.ExpiredSignatureError:
        return None
    except jwt.InvalidTokenError:
        return None
