apiVersion: batch/v1
kind: Job
metadata:
  name: recall-migration
  namespace: incidentfox
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: incidentfox/config-service:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Running Recall.ai migration..."
              cd /app && PYTHONPATH=. alembic upgrade heads
              echo "Migration completed!"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: incidentfox-database-url
                  key: DATABASE_URL
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: recall-schema-registration
  namespace: incidentfox
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: schema-registration
          image: incidentfox/config-service:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Adding Recall.ai integration schema..."
              cd /app && python scripts/add_meeting_schemas.py
              echo "Schema registration completed!"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: incidentfox-database-url
                  key: DATABASE_URL
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
